version: "3.9"
services:
  web:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm ci --omit=dev || npm i --omit=dev; node server.js"
    environment:
      - PORT=3000
      - INSTRUCTOR_KEY=${INSTRUCTOR_KEY:-disabled}
    volumes:
      - ./server:/app:rw
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 6
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

volumes:
  certbot-www: {}
  letsencrypt: {}
